spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 622453710194-sa6nikvm1mhs9pba2500n503a4vu5gfn.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile